//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvalonClient
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvalonEntities : DbContext
    {
        public EvalonEntities()
            : base("name=EvalonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<登录信息表> 登录信息表 { get; set; }
        public virtual DbSet<教师信息表> 教师信息表 { get; set; }
        public virtual DbSet<考试信息表> 考试信息表 { get; set; }
        public virtual DbSet<课程信息表> 课程信息表 { get; set; }
        public virtual DbSet<培养计划表> 培养计划表 { get; set; }
        public virtual DbSet<任课信息表> 任课信息表 { get; set; }
        public virtual DbSet<选课信息表> 选课信息表 { get; set; }
        public virtual DbSet<学生信息表> 学生信息表 { get; set; }
        public virtual DbSet<院系信息表> 院系信息表 { get; set; }
    }
}
