//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvalonClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class 培养计划表
    {
        public long 计划编号 { get; set; }
        public Nullable<int> 系号 { get; set; }
        public string 课程号 { get; set; }
        public Nullable<int> 学期 { get; set; }
    
        public virtual 课程信息表 课程信息表 { get; set; }
        public virtual 院系信息表 院系信息表 { get; set; }
    }
}
