//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvalonClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class 登录信息表
    {
        public string 用户名 { get; set; }
        public string 密码 { get; set; }
        public string 用户类型 { get; set; }
    }
}
