//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvalonClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class 课程信息表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 课程信息表()
        {
            this.考试信息表 = new HashSet<考试信息表>();
            this.培养计划表 = new HashSet<培养计划表>();
            this.任课信息表 = new HashSet<任课信息表>();
            this.选课信息表 = new HashSet<选课信息表>();
        }
    
        public string 课程号 { get; set; }
        public string 课程名称 { get; set; }
        public Nullable<int> 学分 { get; set; }
        public Nullable<int> 学时 { get; set; }
        public string 上课地点 { get; set; }
        public string 上课时间 { get; set; }
        public Nullable<int> 预定人数 { get; set; }
        public Nullable<int> 已选人数 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<考试信息表> 考试信息表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<培养计划表> 培养计划表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<任课信息表> 任课信息表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<选课信息表> 选课信息表 { get; set; }
    }
}
